#!/bin/bash
#SBATCH --partition=thin
#SBATCH --exclusive
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=32
#SBATCH --time=00:30:00
#SBATCH --output=mf6_hbl08_s02_ss_%j.out
#SBATCH --error=mf6_hbl08_s02_ss_%j.err

# load modules
module load 2021
module load iimpi/2021a

sol=s02
mod=glob_hbl08_ss

dir={globgm_dir}/mf6_mod/${mod}/solutions/run_output/
exe={bin_dir}/mf6
nam=${sol}.par.mfsim.ic_sh0.nam

cd ${dir}

srun ${exe} -s ../run_input/${nam}
