#!/bin/bash
#SBATCH --partition=thin
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --output=hbl{pft_lev}_datamap_%j.out
#SBATCH --error=hbl{pft_lev}_datamap_%j.err

lev={pft_lev}
exe={bin_dir}/datamap
out_pref=./map_glob_hbl${lev}
cat={yoda_input}/hybas_lake_lev${lev}_v1c_filt.idf
d={yoda_input}/d_top_2.idf
top={yoda_input}/tile_163.txt
til={yoda_input}/tile_15def_idf/tile_

mkdir {globgm_dir}
cd {globgm_dir}
mkdir ./mf6_map/
cd ./mf6_map/

${exe} 1 ${out_pref} ${cat} ${d} ${top} ${til}
