#!/bin/bash
#SBATCH -t 04:00:00
#SBATCH --output=ss_%j.out
#SBATCH --error=ss_%j.err
#SBATCH -p normal
#SBATCH -N 1

cd {git_dir}/model_tools_src/python/pcr-globwb

python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_001-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_002-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_003-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_004-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_005-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_006-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_007-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_008-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_009-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_010-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_011-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_012-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_013-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_014-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_015-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_016-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_017-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_018-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_019-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_020-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_021-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_022-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_023-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_024-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_025-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_026-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_027-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_028-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_029-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_030-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_031-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_032-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_033-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_034-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_035-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_036-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_037-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_038-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_039-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_040-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_041-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_042-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_043-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_044-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_045-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_046-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_047-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_048-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_049-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_050-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_051-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_052-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_053-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_054-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_055-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_056-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_057-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_058-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_059-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_060-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_061-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_062-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_063-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_064-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_065-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_066-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_067-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_068-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_069-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_070-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_071-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_072-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_073-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_074-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_075-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_076-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_077-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_078-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_079-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_080-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_081-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_082-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_083-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_084-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_085-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_086-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_087-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_088-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_089-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_090-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_091-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_092-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_093-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_094-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_095-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_096-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_097-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_098-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_099-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_100-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_101-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_102-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_103-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_104-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_105-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_106-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_107-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_108-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_109-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_110-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_111-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_112-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_113-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_114-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_115-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_116-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_117-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_118-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_119-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_120-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_121-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_122-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_123-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_124-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_125-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_126-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_127-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_128-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_129-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_130-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_131-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_132-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_133-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_134-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_135-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_136-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_137-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_138-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_139-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_140-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_141-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_142-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_143-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_144-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_145-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_146-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_147-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_148-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_149-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_150-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_151-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_152-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_153-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_154-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_155-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_156-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_157-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_158-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_159-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_160-163 &
wait
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_161-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_162-163 &
python deterministic_runner_for_offline_monthly_modflow.py steady-state_config.ini debug steady-state-only tile_163-163 &
wait
