#!/bin/bash
#SBATCH --partition=thin
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --output=tr_015-028_%j.out
#SBATCH --error=tr_015-028_%j.err


conda activate pcrglobwb_python3

cd {git_dir}/model_tools_src/python/pcr-globwb

python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_015-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_016-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_017-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_018-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_019-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_020-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_021-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_022-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_023-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_024-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_025-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_026-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_027-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_028-163 &
wait
