#!/bin/bash
#SBATCH --partition=thin
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=08:00:00
#SBATCH --output=tr_155-163_%j.out
#SBATCH --error=tr_155-163_%j.err


conda activate pcrglobwb_python3

cd {git_dir}/model_tools_src/python/pcr-globwb

python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_155-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_156-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_157-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_158-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_159-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_160-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_161-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_162-163 &
python deterministic_runner_for_offline_monthly_modflow.py transient_config.ini debug transient tile_163-163 &
wait
